### ISSUE TITLE
delete

### ISSUE THREAD

**Issue by vxna** [gavinanthony/gavinanthony.com#5]
delete

**Comment by vxna** [comment]
Hey @gavinanthony ! 

Sorry for the mess. It was not about the endpoint, but thanks and it will help some :) 
I was about to ask how you watch the results of submitted form: directly on graphcool console, or there is an additional logic on API, like an integration with mailgun email forwarder?

Thanks.

**Comment by gavinbaradic** [comment]
@surepe No worries!

For the contact form, I'm using a Graph.cool endpoint that has a schema called 'ContactForm' with a name, email, and message field. This is integrated with Zapier to send me an email with new database entries.

Looks like this on Graph.cool:

```graphql
type ContactForm implements Node {
  createdAt: DateTime!
  email: String
  id: ID! @isUnique
  message: String
  name: String
  updatedAt: DateTime!
}
```
